---
title: ""
output: 
  html_document:
    theme: cerulean
---
### What is the Living Planet Index?

Developed by Loh et al. (2005), the World Wildlife Fund (WWF), and the Zoological Society of London, the Living Planet Index (LPI) measures the overall global trend in vertebrate abundances since 1970, including terrestrial, freshwater, and marine systems. 

### How should I interpret the Living Planet Index?

#### Uncertainty and biases

### A tool to monitor progress towards global biodiversity objectives

The LPI has served as a popular indicator of global biodiversity change since the first Living Planet Report appeared in 1998, representing two decades of monitoring population-level trends (WWF 2018). This popularity is largely attributable to the LPI’s intuitive association with biodiversity targets, which makes it a powerful tool to communicate the status of biodiversity to decision-makers tasked with the management of biodiversity (Collen et al. 2009). The index is also used to present biodiversity trends to the general public in an accessible way, which incites public engagement in biodiversity issues (Collen et al. 2009). Importantly, the Convention on Biological Diversity (CBD) selected the LPI to monitor progress towards the 2020 Aichi Biodiversity Targets for population abundance trends (CBD 2016). The LPI was also selected as an Essential Biodiversity Variable, solidifying the index as an essential tool for the harmonized study, reporting, and management of biodiversity change worldwide (Pereira et al. 2013).

### How is the Living Planet Index calculated?